server:
  port: 9092
  
spring:
    application:
      name: API-GATEWAY
    cloud:
       gateway:
        routes:
        - id: student-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/student/**
        - id: teacher-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/teacher/**